# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@0
  inputs:
    terraformVersion: 'latest'
- task: TerraformTaskV3@3
  inputs:
    provider: 'aws'
    command: 'init'
    backendServiceAWS: 'service connection-aws'
    backendAWSBucketName: 'fargatebucket-aws'
    backendAWSKey: 'terraform.tfstate'
- task: TerraformTaskV3@3
  inputs:
    provider: 'aws'
    command: 'plan'
    environmentServiceNameAWS: 'service connection-aws'
- task: TerraformTaskV3@3
  inputs:
    provider: 'aws'
    command: 'apply'
    environmentServiceNameAWS: 'service connection-aws'
